### ISSUE TITLE
Code for generating identity.csv

### ISSUE THREAD

**Issue by LinkToPast1990** [BrendanKennedy/contextualizing-hate-speech-models-with-explanations#1]
Hi, could you kindly share the code for generating identity.csv? Thanks!

**Comment by AuCson** [comment]
Hi LMdeLiangMi,

Thanks for your question. We first use `dump_coeff(model, vectorizer)` to dump the coefficients of a linear classifier, as shown in `run_baselines.py`. Then we manually identified 25 group identifiers to construct our identity.csv.
